(function(){
  'use strict';
  const norm=s=>(s||'').replace(/\s+/g,' ').trim().toLowerCase();
  const names={user:['users','user management','manage users'],settings:['settings','account settings','account'],ai:['ai corrections','ai correction','learned ocr corrections','ocr corrections']};
  function findUtility(kind){const ns=names[kind]||[];return [...document.querySelectorAll('button,a,[role="tab"],[data-tab],[data-pane],[data-target]')].find(el=>{if(el.closest('#administrationMenu'))return false;const t=norm(el.textContent),m=norm([el.id,el.getAttribute('data-tab'),el.getAttribute('data-pane'),el.getAttribute('data-target')].join(' '));return ns.some(n=>t===n||m.includes(n))})}
  function hideWorkspace(){const ns=Object.values(names).flat();document.querySelectorAll('button,a,[role="tab"],[data-tab],[data-pane],[data-target]').forEach(el=>{if(el.closest('#administrationMenu'))return;const t=norm(el.textContent),m=norm([el.id,el.getAttribute('data-tab'),el.getAttribute('data-pane'),el.getAttribute('data-target')].join(' '));if(ns.some(n=>t===n||m.includes(n)))el.style.setProperty('display','none','important')})}
  function showUtility(kind,label){const target=findUtility(kind);const old=document.getElementById('adminUtilityModal');if(old)old.remove();const overlay=document.createElement('div');overlay.id='adminUtilityModal';overlay.style.cssText='position:fixed;inset:0;background:rgba(15,23,42,.4);z-index:200000;display:flex;align-items:flex-start;justify-content:center;padding:70px 16px;box-sizing:border-box';const card=document.createElement('div');card.style.cssText='width:min(780px,96vw);max-height:84vh;overflow:auto;background:#fff;border:1px solid #cbd5e1;border-radius:12px;box-shadow:0 24px 60px rgba(0,0,0,.25);padding:18px';const h=document.createElement('div');h.style.cssText='display:flex;justify-content:space-between;align-items:center;margin-bottom:14px';const title=document.createElement('h3');title.textContent=label;title.style.margin='0';const close=document.createElement('button');close.type='button';close.textContent='Close';close.className='btn ghost';close.onclick=()=>overlay.remove();h.append(title,close);card.appendChild(h);if(target){const panel=target.closest('section,.card,.panel,[data-pane]')||target.parentElement;const clone=panel?panel.cloneNode(true):target.cloneNode(true);clone.removeAttribute('id');clone.style.removeProperty('display');clone.style.setProperty('display','block','important');clone.querySelectorAll('[style*="display: none"]').forEach(x=>x.style.removeProperty('display'));card.appendChild(clone);clone.querySelectorAll('button,a').forEach(x=>{x.addEventListener('click',()=>{try{target.click()}catch(_){}})});}else{const p=document.createElement('p');p.textContent='Administration feature unavailable.';card.appendChild(p)}overlay.appendChild(card);overlay.onclick=e=>{if(e.target===overlay)overlay.remove()};document.body.appendChild(overlay)}
  function build(){if(document.getElementById('administrationNav'))return;const host=document.querySelector('.gov-user-panel,header nav,header,.topbar,.navbar,.nav-bar,.app-header,.header-actions')||document.body;const nav=document.createElement('div');nav.id='administrationNav';nav.style.cssText='position:relative;display:inline-flex;align-items:center;z-index:200001;margin:6px 10px 6px 8px';if(host===document.body)nav.style.cssText+='position:fixed;top:8px;right:12px;margin:0;';const b=document.createElement('button');b.type='button';b.textContent='Administration';b.className='btn ghost';b.style.cssText='padding:7px 13px;font-size:12px;font-weight:600;cursor:pointer';const menu=document.createElement('div');menu.id='administrationMenu';menu.style.cssText='display:none;position:absolute;right:0;top:calc(100% + 5px);width:230px;background:#fff;border:1px solid #cbd5e1;border-radius:10px;padding:6px;box-shadow:0 14px 32px rgba(0,0,0,.2);z-index:200002';[['Users','user'],['Settings','settings'],['AI Corrections','ai']].forEach(([label,k])=>{const x=document.createElement('button');x.type='button';x.textContent=label;x.className='btn ghost';x.style.cssText='display:block;width:100%;text-align:left;border:0;padding:10px 11px;font-size:12px';x.onclick=e=>{e.stopPropagation();menu.style.display='none';showUtility(k,label)};menu.appendChild(x)});const land=document.createElement('a');land.href='/land-intelligence';land.textContent='Land Intelligence';land.className='btn ghost';land.style.cssText='display:block;width:100%;box-sizing:border-box;text-align:left;border:0;padding:10px 11px;font-size:12px;text-decoration:none';menu.appendChild(land);const sep=document.createElement('div');sep.style.cssText='height:1px;background:#e2e8f0;margin:5px 0';menu.appendChild(sep);const out=document.createElement('button');out.type='button';out.textContent='Log out';out.className='btn ghost';out.style.cssText='display:block;width:100%;text-align:left;border:0;padding:10px 11px;font-size:12px';out.onclick=()=>{const real=document.querySelector('#logoutBtn,[data-action="logout"],[data-logout]');if(real)real.click();else window.location.href='/'};menu.appendChild(out);b.onclick=e=>{e.stopPropagation();menu.style.display=menu.style.display==='none'?'block':'none'};nav.append(b,menu);host===document.body?document.body.appendChild(nav):host.insertBefore(nav,host.firstChild)}
  function run(){build();hideWorkspace()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();new MutationObserver(run).observe(document.documentElement,{subtree:true,childList:true});document.addEventListener('click',e=>{if(!e.target.closest('#administrationNav')){const m=document.getElementById('administrationMenu');if(m)m.style.display='none'}},true);
})();
