(()=>{'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function auth(){try{const t=localStorage.getItem('lrtoken');return t?{Authorization:'Bearer '+t}:{} }catch(_){return{}}}
async function get(url){const r=await fetch(url,{headers:{...auth(),Accept:'application/json'},cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.detail||'Unable to load data');return d}
function value(o){return o&&typeof o==='object'&&'value' in o?o.value:o}
function draw(m){const box=$('#detail'),g=m.geometry,p=m.coordinates;let shape='';if(g){const pts=[];const walk=v=>{if(Array.isArray(v)){if(v.length>=2&&typeof v[0]==='number')pts.push([v[0],v[1]]);else v.forEach(walk)}};walk(g.coordinates);if(pts.length){const xs=pts.map(x=>x[0]),ys=pts.map(x=>x[1]),minx=Math.min(...xs),maxx=Math.max(...xs),miny=Math.min(...ys),maxy=Math.max(...ys),sx=250/Math.max(maxx-minx,1e-9),sy=220/Math.max(maxy-miny,1e-9),s=Math.min(sx,sy),px=pts.map(x=>`${45+(x[0]-minx)*s},${250-(x[1]-miny)*s}`).join(' ');shape=`<polyline points="${esc(px)}" fill="none" stroke="currentColor" stroke-width="3"/><circle cx="${esc(45+(pts[0][0]-minx)*s)}" cy="${esc(250-(pts[0][1]-miny)*s)}" r="6" fill="currentColor"/>`}}}else if(p)shape=`<circle cx="50%" cy="50%" r="9" fill="currentColor"/>`;const map=`<div class="mapbox"><svg viewBox="0 0 340 280" preserveAspectRatio="xMidYMid meet">${shape||'<text x="170" y="140" text-anchor="middle" fill="#667085">No geometry in document</text>'}</svg></div>`;const loc=m.location_fields||{};box.innerHTML=`<h2>Document details</h2>${map}<div class="kv">${Object.entries(loc).filter(([,v])=>v).map(([k,v])=>`<div><small>${esc(k.replaceAll('_',' '))}</small><b>${esc(value(v))}</b></div>`).join('')} ${p?`<div><small>Coordinates</small><b class="coords">${esc(p.latitude)}, ${esc(p.longitude)}</b></div>`:''}<div><small>Mapping method</small><b>${esc(m.method)}</b></div><div><small>Source</small><b>Uploaded document record</b></div></div>${p?`<a class="link" href="https://www.openstreetmap.org/?mlat=${encodeURIComponent(p.latitude)}&mlon=${encodeURIComponent(p.longitude)}" target="_blank" rel="noopener">Open coordinates externally →</a>`:''}`}
async function openDoc(id){try{const d=await get('/api/land/document-map/'+encodeURIComponent(id));draw(d.mapping||{})}catch(e){$('#detail').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function load(){const rows=$('#rows');try{const [s,ds]=await Promise.all([get('/api/land/document-map/summary'),get('/api/land/document-map/documents')]);$('#total').textContent=s.total_documents;$('#mapped').textContent=s.mapped_documents;$('#unmapped').textContent=s.unmapped_documents;$('#low').textContent=s.low_confidence;const statuses=Object.keys(s.status_counts||{});$('#status').innerHTML='<option value="">All statuses</option>'+statuses.map(x=>`<option>${esc(x)}</option>`).join('');window.docs=ds.documents||[];render()}catch(e){rows.innerHTML=`<tr><td colspan="6" class="empty">${esc(e.message)}</td></tr>`}}
function render(){const q=($('#search').value||'').toLowerCase().trim(),st=$('#status').value.toLowerCase(),mf=$('#mappedFilter').value;const docs=(window.docs||[]).filter(d=>{const hay=JSON.stringify(d).toLowerCase();return(!q||hay.includes(q))&&(!st||String(d.status||'').toLowerCase()===st)&&(mf===''||String(d.mapped)===mf)});$('#rows').innerHTML=docs.length?docs.map(d=>{const l=d.location||{},ident=l.survey_number||l.gat_number||l.khasra_number||'—',place=[l.village,l.taluka,l.district].filter(Boolean).join(', ')||'—';return `<tr><td><div class="doc">${esc(d.filename||d.id)}</div><div class="sub">${esc(d.doc_type||'')} · #${esc(d.id)}</div></td><td>${esc(ident)}</td><td>${esc(place)}</td><td><span class="badge">${esc(d.status||'UNKNOWN')}</span></td><td><span class="badge ${d.mapped?'mapped':'unmapped'}">${d.mapped?'Available':'Not found'}</span></td><td><button class="open" data-id="${esc(d.id)}">Inspect</button></td></tr>`}).join(''):'<tr><td colspan="6" class="empty">No documents match your filters.</td></tr>';document.querySelectorAll('.open').forEach(b=>b.onclick=()=>openDoc(b.dataset.id))}
$('#search').oninput=render;$('#status').onchange=render;$('#mappedFilter').onchange=render;$('#refresh').onclick=load;load();
})();