(()=>{'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function auth(){try{const t=localStorage.getItem('lrtoken');return t?{Authorization:'Bearer '+t}:{} }catch(_){return{}}}
async function get(url){const r=await fetch(url,{headers:{...auth(),Accept:'application/json'},cache:'no-store'});let d={};try{d=await r.json()}catch(_){}if(!r.ok)throw Error(d.detail||'Unable to load data');return d}
const map=L.map('map',{zoomControl:true,worldCopyJump:false});
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
map.setView([20.5937,78.9629],4);let layer=L.layerGroup().addTo(map),selected=null;
function value(v){return v&&typeof v==='object'&&'value'in v?v.value:v}
function clearLayer(){layer.clearLayers();selected=null}
function popup(d){const l=d.location||{},place=[l.village,l.taluka,l.district].filter(Boolean).join(', ')||'Location fields only';return `<b>${esc(d.filename||'Document #'+d.id)}</b><br>${esc(place)}<br><span>${esc(d.status||'UNKNOWN')}</span>`}
function plot(d,fit=true){clearLayer();const g=d.geometry,p=d.coordinates,all=[];
 if(g){const geo=L.geoJSON(g,{style:{weight:3,fillOpacity:.18}}).bindPopup(popup(d));geo.addTo(layer);all.push(geo.getBounds())}
 if(p){const marker=L.marker([p.latitude,p.longitude]).bindPopup(popup(d));marker.addTo(layer);all.push(L.latLngBounds([[p.latitude,p.longitude],[p.latitude,p.longitude]]))}
 if(all.length&&fit){let bounds=all[0];for(let i=1;i<all.length;i++)bounds=bounds.extend(all[i]);map.fitBounds(bounds,{padding:[35,35],maxZoom:p&&!g?16:17})}
 $('#mapState').textContent=p||g?'Document location loaded':'No coordinates or geometry in this document';
}
function risk(status,cls){const label=cls==='attention'?'Needs attention':cls==='verified'?'Screening passed':'Review status';return `<div class="risk ${esc(cls)}">${esc(label)} · ${esc(status||'UNKNOWN')}</div>`}
function drawDetail(d){const box=$('#detail'),doc=d.document||{},m=d.mapping||{},l=m.location_fields||{};const fields=Object.entries(l).filter(([,v])=>v).map(([k,v])=>`<div><small>${esc(k.replaceAll('_',' '))}</small><b>${esc(value(v))}</b></div>`).join('');const p=m.coordinates;box.innerHTML=`<h2>${esc(doc.filename||'Document')}</h2><div class="sub">#${esc(doc.id)} · ${esc(doc.doc_type||'')}</div>${risk(doc.status,doc.status_class)}<div class="kv"><div><small>Screening confidence</small><b>${doc.confidence==null?'Not available':esc(doc.confidence)+'%'}</b></div>${fields}<div><small>Mapping method</small><b>${esc(m.method)}</b></div><div><small>Data source</small><b>Uploaded document record</b></div></div><div class="hint">${esc(m.message||'No map data found. The system does not invent a location.')}</div>${p?`<a class="link" href="https://www.openstreetmap.org/?mlat=${encodeURIComponent(p.latitude)}&mlon=${encodeURIComponent(p.longitude)}#map=17/${encodeURIComponent(p.latitude)}/${encodeURIComponent(p.longitude)}" target="_blank" rel="noopener">Open coordinates externally →</a>`:''}`}
async function openDoc(id){try{const d=await get('/api/land/document-map/'+encodeURIComponent(id));drawDetail(d);plot(d.mapping||{});document.querySelectorAll('tr[data-doc]').forEach(x=>x.classList.toggle('selected',x.dataset.doc===String(id)))}catch(e){$('#detail').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function load(){const rows=$('#rows');try{const [s,ds]=await Promise.all([get('/api/land/document-map/summary'),get('/api/land/document-map/documents')]);$('#total').textContent=s.total_documents;$('#mapped').textContent=s.mapped_documents;$('#unmapped').textContent=s.unmapped_documents;$('#low').textContent=s.low_confidence;const statuses=Object.keys(s.status_counts||{});$('#status').innerHTML='<option value="">All statuses</option>'+statuses.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');window.docs=ds.documents||[];render()}catch(e){rows.innerHTML=`<tr><td colspan="6" class="empty">${esc(e.message)}</td></tr>`}}
function render(){const q=($('#search').value||'').toLowerCase().trim(),st=$('#status').value.toLowerCase(),mf=$('#mappedFilter').value;const docs=(window.docs||[]).filter(d=>{const hay=JSON.stringify(d).toLowerCase();return(!q||hay.includes(q))&&(!st||String(d.status||'').toLowerCase()===st)&&(mf===''||String(d.mapped)===mf)});$('#rows').innerHTML=docs.length?docs.map(d=>{const l=d.location||{},ident=l.survey_number||l.gat_number||l.khasra_number||l.khata_number||'—',place=[l.village,l.taluka,l.district].filter(Boolean).join(', ')||'—';return `<tr data-doc="${esc(d.id)}"><td><div class="doc">${esc(d.filename||d.id)}</div><div class="sub">${esc(d.doc_type||'')} · #${esc(d.id)}</div></td><td>${esc(ident)}</td><td>${esc(place)}</td><td><span class="badge ${esc(d.status_class||'review')}">${esc(d.status||'UNKNOWN')}</span></td><td><span class="badge ${d.mapped?'mapped':'unmapped'}">${d.mapped?'Available':'Not found'}</span></td><td><button class="open" data-id="${esc(d.id)}">Inspect</button></td></tr>`}).join(''):'<tr><td colspan="6" class="empty">No documents match your filters.</td></tr>';document.querySelectorAll('.open').forEach(b=>b.onclick=()=>openDoc(b.dataset.id))}
$('#search').oninput=render;$('#status').onchange=render;$('#mappedFilter').onchange=render;$('#refresh').onclick=load;window.addEventListener('resize',()=>map.invalidateSize());load();
})();